config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root"chatrooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  
  has_many :chatroom_users, dependent: :destroy
  
  has_many :users, through: :chatroom_users
  # has_many :users, through: :chatroom_users, source: :user

  has_many :messages


end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chatroom_users, dependent: :destroy
  has_many :chatrooms, through: :chatroom_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

end

app/controllers/chatroom_users_controller.rb
# class ChatroomUsersController < ApplicationController
#   before_action :authenticate_user!
#   before_action :set_chatroom
  
#   def create
#     # render html:params
      #first_or_create可以確保只添加一次（已存在就不再多寫)
#     @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
#     redirect_to @chatroom

#   end

#   def destroy
#     @chatroom_user=@chatroom.chatroom_users.where(user_id: current_user.id).destroy_all
#     redirect_to chatrooms_path
#   end

#  private
#   def set_chatroom
#     @chatroom=Chatroom.find(params[:chatroom_id])
#   end

#   def find_chatroom_user
#     @chatroom_user=@chatroom.chatroom_users.find(user_id: current_user.id)
#   end
# end

class ChatroomUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom, only: [:create ,:destroy]
  
  def create
    @chatroom_user = @chatroom.chatroom_users.find_or_create_by(user_id: current_user.id)
    redirect_to @chatroom
  end

  def destroy
    # 直接從本體找本體（路過through）
    current_user.chatrooms.delete(@chatroom)

    # wrong number of arguments (given 0, expected 1)
    # @chatroom.chatroom_users.where(user_id: current_user.id).destroy

    # 另一種寫法(從第三方表格去找)
    # @chatroom.chatroom_users.find_by(user_id: current_user.id).delete
    
    redirect_to chatrooms_path
  end

 private
  def set_chatroom
    @chatroom = Chatroom.find(params[:chatroom_id])
  end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: %i[ show edit update destroy ]

  # GET /chatrooms or /chatrooms.json
  def index
    @chatrooms = Chatroom.all
    
  end

  # GET /chatrooms/1 or /chatrooms/1.json
  def show
    @messages = @chatroom.messages.order(create_at: :desc).limit(15).reverse
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms or /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to chatroom_url(@chatroom), notice: "Chatroom was successfully created." }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1 or /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to chatroom_url(@chatroom), notice: "Chatroom was successfully updated." }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1 or /chatrooms/1.json
  def destroy
    @chatroom.destroy

    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: "Chatroom was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom

  def new
    @message=@chatroom.messages.new
  end

  def create
    @message=@chatroom.messages.new(messages_params)
    @message.user=current_user

    if @message.save
      notice: "已傳送"
    else
      notice: "發送失敗"
    end
  end

  private
  def set_chatroom
    @chatroom = Chatroom.find(params[:chatroom_id])
  end

  def messages_params
    params.require(:message).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chatrooms/_form.html.erb
<%= form_with(model: chatroom) do |form| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
        <% chatroom.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chatrooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chatrooms.each do |chatroom| %>
      <tr>
        <td><%= chatroom.name %></td>
        <td><%= link_to 'Show', chatroom %></td>
        <td><%= link_to 'Edit', edit_chatroom_path(chatroom) %></td>
        <td><%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'join', chatroom_chatroom_users_path(chatroom), method: "post" %></td>
        <td><%= link_to 'leave', chatroom_chatroom_users_path(chatroom), method:"delete" %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chatroom', new_chatroom_path %>

app/views/chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chatroom.name %>
</p>


<div class="comments" data-behavior='messages'>
  <% @messages.each do |message| %>
    <div><strong><%= message.user.username %></strong><%= message.body %></div>
  <% end %>
</div>

  <%# <%= form_for [@chatroom, Message.new], remote: true do |form| %> %>
  <%# <%= form_with(model: @messages, url: chatroom_messages_path(@chatroom), local: false)do |form| %> %>
  <%= form_for [@chatroom, Message.new] do |form| %>
    <div id="comment_content">
      <%= form.text_area :body, rows: 1, class: "form-control" ,autofocus: true %>
    </div>
    
    <%= form.submit %>
  
  <% end %>











<%= link_to 'Edit', edit_chatroom_path(@chatroom) %> |
<%= link_to 'Back', chatrooms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <nav class="navbar-fixed-top">
    <div class="row">
      <%= link_to "sign up" , new_user_registration_path %>
      <%= link_to "sign in" , new_user_session_path %>
      <%= link_to "edit" , edit_user_registration_path %>
      <%= link_to "sign out" , destroy_user_session_path, method:"delete" %>
    </div>
  </nav>


  


  <div class="fluid-container"  style="margin-top: 30px">
      <div class="row">
        <div class="col-sm-2" style="position: fixed">
            <% if user_signed_in? %>
              <h5 class="text-danger">chatroomYOOOO</h5>
              <ul>
                <% current_user.chatrooms.each do |chatroom| %>
                  <%= link_to chatroom.name ,chatroom_path(chatroom) %>
                <%end%>
              </ul>
            <% end %>
        </div>
        <div class="col-sm-2" style="left: 20%">
          <%= yield %>
        </div>
      </div>
    </div>

    
    
  </body>
</html>

app/views/messages/create.js.erb
var comments = document.querySelector('.comments')
var li = "<%= comment.content %>"
comments.insertAdjacentHTML("beforeend", li)
document.querySelector('#comment_content').value = ''